services:
  backend:
    build:
      context: ./backend

    environment:
      DATABASE_PATH: /data/news.db

    volumes:
      - news-data:/data

    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "8085:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  news-data: